### ISSUE TITLE
responsive menu on mobile device

### ISSUE THREAD

**Issue by auth1299** [huntlyc/wp-bootstrap-theme#1]
There seems to be an issue with the navigation menu when using it on a mobile device. The problem happens if you have more than 2 layers of sub menus. You can not navigate past 2 layers.

**Comment by huntlyc** [comment]
Hey, thanks for this.  To be fair, it's using bootstrap 2 and needs a bit of an update....  I did just commit a custom walker to output a 2 level nav correctly which might somewhat help (b3b44a0fe9e69b0e90019119e84280aa910c9f9b)
